SELECT USR.USER_ID, USR.NICKNAME, SUM(UGB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD UGB
INNER JOIN USED_GOODS_USER USR ON USR.USER_ID = UGB.WRITER_ID
WHERE UGB.STATUS = 'DONE'
GROUP BY USR.USER_ID, USR.NICKNAME
HAVING SUM(UGB.PRICE) >= 700000
ORDER BY TOTAL_SALES ASC
/*
최적화 쿼리 
굳이 서브쿼리를 사용할 필요가 없음 -> 자원 낭비
*/



SELECT USR.USER_ID , USR.NICKNAME, AMT.TOTAL as TOTAL_SALES from 
(SELECT WRITER_ID,sum(PRICE) as TOTAL from USED_GOODS_BOARD  WHERE STATUS='DONE' GROUP BY(WRITER_ID) ) as AMT 
inner join USED_GOODS_USER as USR ON USR.USER_ID =AMT.WRITER_ID 
WHERE AMT.TOTAL>=700000
ORDER BY AMT.TOTAL ASC
/*
기존 쿼리
*/