WITH USR AS(
    SELECT WRITER_ID, COUNT(1) AS CNT FROM USED_GOODS_BOARD GROUP BY WRITER_ID 
    HAVING CNT>=3
)

SELECT U.USER_ID, U.NICKNAME,   
CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ',U.STREET_ADDRESS2) AS 전체주소,
CONCAT(SUBSTR(U.TLNO,1,3),'-',SUBSTR(U.TLNO,4,4),'-',SUBSTR(U.TLNO,8,4))
AS 전화번호
FROM USED_GOODS_USER AS U WHERE U.USER_ID IN (SELECT WRITER_ID FROM USR)
ORDER BY U.USER_ID DESC